#!/bin/bash
switch=ovs-br0
ovs_var_run=/usr/local/var/run/openvswitch
OVS_PATH=/home/haizhi/qemu-lab/ovs-bin/
OVS_SBIN_PATH=${OVS_PATH}/sbin/
OVS_BIN_PATH=${OVS_PATH}/bin/

if [ -n "$1" ]; then
	ip link set $1 up
	echo "[SHELL]qemu-ovs-ifup, run cmd: [ovs-vsctl add-port $switch $1]"
	${OVS_BIN_PATH}/ovs-vsctl --db=unix:${ovs_var_run}/db.sock add-port ${switch} $1
	exit 0
else
	echo "Error: no interface specified!!!!"
	exit 1
fi
