#!/bin/bash
TAP=$1
if [ "X$TAP" == "X" ];then
	echo "[Error] tap nic is null!!!"
	exit 1;
fi
NUM=$(echo ${TAP} | sed 's/[^0-9]//g')
switch=br${NUM}
if [ -n "${TAP}" ]; then
	ip link set ${TAP} down
	echo "run cmd: [brctl delif $switch ${TAP}]"
	brctl delif ${switch} ${TAP}

	ip link set ${switch} down
	brctl delbr ${switch}
	exit 0
else
	echo "Error: no interface specified!!!!"
	exit 1
fi
